language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

matrix:
   fast_finish: true
   include:
   - go: 1.11.x
     env: GO111MODULE=on

services:
  - mysql

# create test database
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db1;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db2;'
  - export MYSQL_TEST_DSN1="travis:@/db1?parseTime=true"
  - export MYSQL_TEST_DSN2="travis:@/db2?parseTime=true"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=321465c4ca2e032caea5e3daf85124c1ba894c986df8f4903c525477e9bdb14f