name: gosql
on: [push, pull_request]
jobs:
  test:
#    strategy:
#      matrix:
#        go-version: [1.10.8, 1.11, 1.12, 1.13]
    runs-on: ubuntu-latest
#    services:
#      mysql:
#        image: mysql:5.7.27
#        ports:
#          - 3306
#        volumes:
#          - $HOME/mysql:/var/lib/mysql
#        env:
#          MYSQL_ROOT_PASSWORD: 123456
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Init Database
        run: |
          mysql -urunner -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS db1;'
          mysql -urunner -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS db2;'

      - name: Test
        env:
          MYSQL_TEST_DSN1: "runner:@tcp(127.0.0.1:3306)/db1?parseTime=true"
          MYSQL_TEST_DSN2: "runner:@tcp(127.0.0.1:3306)/db2?parseTime=true"
        run: go test ./...